### ISSUE TITLE
我star你了还不行么

### ISSUE THREAD

**Issue by RoyWallace** [liaohuqiu/android-support-23.2-sample#2]
停下你刷存在感的脚本吧

**Comment by Piasy** [comment]
我说呢。。。

**Comment by liaohuqiu** [comment]
1.  非常抱歉。
2.  如果不喜欢，不感兴趣，或者任何原因，导致你不开心。请取消关注。
3.  谢谢你之前的的关注和支持。

**Comment by Piasy** [comment]
哈哈，只是突然懂了 😀

**Comment by liaohuqiu** [comment]
@Piasy 这并不需要什么脚本，一个 Toggle 操作就好了。在东八区早上和太平洋时间各操作一次，这样两边的人都会看到，和转推，转发一样。

不喜欢这样的话，取消关注吧。非常抱歉给你带来困扰。

**Comment by Piasy** [comment]
soga，原来还是手动的

倒没有觉得不爽，只是每天东八区早上看feed的时候发现你在反复star自己，其实我膜拜你有一段时间了，希望有机会可以[向你取经🐒](https://github.com/Piasy/JourneyToTheTruth)

**Comment by liaohuqiu** [comment]
@Piasy 看起来很像暗杀黑名单啊。我过段时间回国之后，搞个 Meetup。

**Comment by Piasy** [comment]
😄太赞了！

**Comment by RoyWallace** [comment]
我开个玩笑而已
